prooph_event_store:
    stores:
        default:
            event_store: 'app.event_store.default'
            repositories:
                account_collection:
                    repository_class: App\Service\EventStoreAccountCollection
                    aggregate_type: App\Model\Account\Account
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

    projection_managers:
        default_projection_manager:
            event_store: 'app.event_store.default'
            connection: 'doctrine.pdo.connection'
            projections:
                account_projection:
                    read_model: App\Projection\Account\AccountReadModel
                    projection: App\Projection\Account\AccountProjection
                transaction_projection:
                    read_model: App\Projection\Transaction\TransactionReadModel
                    projection: App\Projection\Transaction\TransactionProjection

services:
    _defaults:
        public: false

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]
