prooph_service_bus:
    command_buses:
        default_command_bus:
            router:
                type: 'prooph_service_bus.command_bus_router'
    event_buses:
        default_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
    query_buses:
        default_query_bus: ~

services:
    _defaults:
        public: false

    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.default_command_bus'
