prooph_event_store:
    stores:
        default:
            event_store: 'app.event_store.default'
            repositories:
                account_collection:
                    repository_class: App\Service\EventStoreAccountCollection
                    aggregate_type: App\Model\Account\Account
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

services:
    _defaults:
        public: false

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~
