version: '3'
services:

#  mysql:
#    image: mysql:5.7
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=dev
#      - MYSQL_USER=dev
#      - MYSQL_PASSWORD=dev
#      - MYSQL_DATABASE=todo
#    volumes:
#      - ./vendor/prooph/pdo-event-store/scripts/mysql:/docker-entrypoint-initdb.d

  webserver:
    image: php:7-apache
    working_dir: /var/www/
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
    command: bash -c "a2enmod rewrite && apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_mysql pdo_pgsql && apache2-foreground"

  database:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bank_account
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 33060:3306

#  projection_todo:
#    image: prooph/php:7.1-cli
#    entrypoint:
#      - /app/.docker/wait_for_sql.sh
#    volumes:
#      - .:/app
#    depends_on:
#      - mysql
#    command: php bin/console event-store:projection:run todo_projection
#
#  projection_todo_reminder:
#    image: prooph/php:7.1-cli
#    entrypoint: /app/.docker/wait_for_sql.sh
#    volumes:
#      - .:/app
#    depends_on:
#      - mysql
#    command: php bin/console event-store:projection:run todo_reminder_projection
#
#  projection_user:
#    image: prooph/php:7.1-cli
#    entrypoint: /app/.docker/wait_for_sql.sh
#    volumes:
#      - .:/app
#    depends_on:
#      - mysql
#    command: php bin/console event-store:projection:run user_projection

# Uncomment when using snapshotters
# @TODO: Implement snapshot projections, see proophessor-do
#  snapshotter_todo:
#    image: prooph/php:7.1-cli
#    entrypoint: /app/.docker/wait_for_sql.sh
#    volumes:
#      - .:/app
#    depends_on:
#      - mysql
#      - mongodb
#    command: php /app/bin/todo_snapshotter.php
#
#  snapshotter_user:
#    image: prooph/php:7.1-cli
#    entrypoint: /app/.docker/wait_for_sql.sh
#    volumes:
#      - .:/app
#    depends_on:
#      - mysql
#      - mongodb
#    command: php /app/bin/user_snapshotter.php
