#index:
#    path: /
#    controller: App\Controller\DefaultController::index
command::register-account:
  path: /commands/register-account
  defaults: { _controller: App\Controller\CommandController:command, command_name: 'App\Model\Command\RegisterAccount' }

command::deposit:
  path: /commands/deposit
  defaults: { _controller: App\Controller\CommandController:command, command_name: 'App\Model\Command\DepositAccount' }

command::withdraw:
  path: /commands/withdraw
  defaults: { _controller: App\Controller\CommandController:command, command_name: 'App\Model\Command\WithdrawAccount' }

account:show:
  path: /account/show/{accountNumber}
  controller: App\Controller\AccountController::show

account:transactions:
  path: /account/transactions/{accountNumber}
  controller: App\Controller\AccountController::transactions